### PR TITLE
blank page on first load due to previous patch

### PR DESCRIPTION
**Pull request by bragle**
Turns out that my previous patch didn't work quite as intended. Now, on first load, a blank page is shown. Echoing $content instead of setting \Craft::$app->response->data to $content works fine, but I see no reason not to just serve the original output buffer.

### CODE REVIEW

**Comment by bragle** [comment]
I added an option to remove whitespace from the cached file. You can add that if you want to :)

**Comment by stursby** [comment]
@bragle I too am getting a white/blank page on first load.

**Comment by boldenamsterdam** [comment]
@stursby I cannot replicate the issue with my setup.
@bragle Does this pull fix the white page issue? If yes then I will merge and release it.

**Comment by bragle** [comment]
It does, but it also adds an option for whitespace removal when caching. If you want that, you can merge, but if you only want the white page fix, I can remove the added functionality.

**Pull request merged**
